### ISSUE TITLE
ggplot2 logic in visualization

### ISSUE THREAD

**Issue by durszlaczek** [MI2DataLab/factorMerger#18]
It'd be great to change plotting function to be consistent with ggplot, e.g. 
`ggfmtree(factorMerger, "pval") + geom_diagnostics(alpha = "pval") + geom_heatmap(palette = 'Reds')`

**Comment by pbiecek** [comment]
Would be great

**Comment by pbiecek** [comment]
maybe in factorMerger2.
IMHO the syntax should be frozen, the only exceptions are small changes in argument names
