### ISSUE TITLE
Use case - TCGA

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/factorMerger#32]
Clinical data:
```
library(RTCGA.clinical)
patient.drugs.drug.drug_name # drug name
patient.days_to_last_known_alive # time
patient.days_to_death # NA - still alive
patient.days_to_last_followup #

patient.clinical_cqcf.histological_type # subtype

substr(BRCA.clinical$patient.stage_event.tnm_categories.pathologic_categories.pathologic_t, 1, 2) # tnm category T1-T4
```

**Comment by durszlaczek** [comment]
Tutaj: [https://rawgit.com/geneticsMiNIng/FactorMerger/master/materials/brca.html](https://rawgit.com/geneticsMiNIng/FactorMerger/master/materials/brca.html) są jakieś wyniki. 

Nieco rażą w oczy nierówno rozmieszczone wykresy "tree" i "GIC"

**Comment by pbiecek** [comment]
Wyniki dla leków są bardzo fajne,
(1) być może problem wyrównania wykresów można tak rozwiązać, że na osi GICa będą nie wartości kryterium ale nazwy ostatnio sklejonej grupy?
(2) na takiem wykresie świetnie byłoby też pokazać wynik testu posthoc (niespójny), co więcej, to chyba da się zrobić, do dyskusji
