### ISSUE TITLE
Usecase PISA 2015

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/factorMerger#34]
Grupowanie zawodów rodziców, zmienne OCOD1 i OCOD2

**Comment by durszlaczek** [comment]
Użyłam danych z 2012, a zamiast zmiennych OCOD skorzystałam z klasyfikacji zawodów iso08 (około 50 poziomów, dane znajdują się w `data/iso08codes.rda`)

**Comment by pbiecek** [comment]
Przydałyby się też html w katalogu materials (tak jak dla BRCA), bardzo ułątwia to oglądanie wyników.
