### ISSUE TITLE
hclust - use "complete" method only

### ISSUE THREAD

**Issue by durszlaczek** [MI2DataLab/factorMerger#42]

**Comment by pbiecek** [comment]
see #47

**Comment by durszlaczek** [comment]
What is implemented is not the exact form of the "complete" hclust.
Here I assumed that if we three groups - A, B, C - sorted by their effects (i.e. means, mu(A) < mu(B) < mu(C)), then the distance between A and B is not greater than the distance between A and C (similarly,  the distance between B and C is not greater than the distance between A and C). This is not always true, as the distance matrix in DMR is based on the LRT statistic in which standard deviation is also taken under consideration.

**Comment by pbiecek** [comment]
this discussion shall be included to the article/man-page
