### ISSUE TITLE
HPC test on bigger data

### ISSUE THREAD

**Issue by MarcinKosinski** [MI2DataLab/factorMerger#44]
@Durszlaczek have you ever tried to test mergeFactors on a data ~7mln observations and 70 levels in the factor for a `family='survival'`? Do you think this is doable?

**Comment by MarcinKosinski** [comment]
If the process in any way is iterative, do you think the mergeFactors could `cat` the progress of computations / algorithm? So that one can calculate the time point in which calculations will finish. 🎆

**Comment by pbiecek** [comment]
Try 'method = "hclust"' for large number of levels. 
This will speed up the merging procedure.
And expect some improvements related to timings of calculations in next versions.

**Comment by durszlaczek** [comment]
@MarcinKosinski, for a bit of a speedup you can also try to use `successive = TRUE` in `mergeFactors`.

I'll think of adding some progress tracking in next updates.

**Comment by MarcinKosinski** [comment]
Closing this, as this is not an issue that can be resolved. 
I wonder there exist platforms for projects where people could post random thoughts

**Comment by pbiecek** [comment]
mi2datalab.slack.com ;-)
let me know if your are not there

**Comment by MarcinKosinski** [comment]
I'm not. I'd like to join, if this is possible :)
Also, have you considered https://gitter.im/ ?
