### ISSUE TITLE
replace `method` and `successive` by fuse

### ISSUE THREAD

**Issue by pbiecek** [MI2DataLab/factorMerger#47]
What about using a single argument `fuse` instead of two `method` and `successive`?

```
fuse = “all2all” | Compare all pairs of groups
fuse = “nearby” | Compare nearby groups
fuse = “cluster” | DMR4glm algorithm
```

**Comment by durszlaczek** [comment]
@pbiecek, the `fuse` you described would work well if we had only one type of the DMR strategy (original DMR4glm, I guess). I think for really large data it is beneficial to have also the successive version of the DMR as it is the fastest algorithm.

**Comment by pbiecek** [comment]
Ok, this convinced me, 
but we should not use 'DMR' name for it, since we do not know if asymptotic properties of DMR still holds.
so maybe `fuse = "fast / approximate"`?

**Comment by durszlaczek** [comment]
I replaced `method` and `successive` with one argument with levels:
`method = “adaptive”` | Compare all pairs of groups, recalculate likelihood for all groups in each step,
`method = "fast-adaptive”` | Compare nearby groups, recalculate likelihood for all groups in each step,
`method = “fixed”` | Compare all pairs of groups, keep the distance matrix fixed (DMR4glm algorithm),
`method = “fast-fixed` | Compare nearby groups, keep the distance matrix fixed.
