### ISSUE TITLE
mergeFactors - factors with empty levels

### ISSUE THREAD

**Issue by agosiewska** [MI2DataLab/factorMerger#51]
The function `mergeFactors` doesn't work with factors with unused levels.
Example:
```
library(factorMerger)
fdata <- rep(c(1,2), 100)
fdata2 <- factor(rep(c("a","b"), 100))
levels(fdata2) <- c("a","b","c")
x <- mergeFactors(fdata, fdata2)
```
A possible solution may be the `droplevels` function.

**Comment by durszlaczek** [comment]
Thanks, @agosiewska. That has been fixed.
