### ISSUE TITLE
Compare factorMerger results between current and previous pisa2012 data 

### ISSUE THREAD

**Issue by durszlaczek** [MI2DataLab/factorMerger#55]
Current `pisa2012` dataset is created on different seed than the previous one. Please compare results obtained by **factorMerger** for both datasets.

**Comment by pbiecek** [comment]
the previous dataset gives results closer to the ,,official final''
(Finland before Poland https://www.theguardian.com/news/datablog/2013/dec/03/pisa-results-country-best-reading-maths-science)
