### ISSUE TITLE
Alternating palette for clusters 

### ISSUE THREAD

**Issue by durszlaczek** [MI2DataLab/factorMerger#58]
If the number of cluster chosen is large it is hard to distinguish between adjacent clusters. 
Maybe an alternating palette will help with this problem?
Below there is an example how this issue may be solved (from:  http://dx.doi.org/10.1080/10618600.2017.1305277)
![screenshot from 2017-09-28 14-33-01](https://user-images.githubusercontent.com/14364483/30967122-777c2d00-a45b-11e7-85cd-0a122fe3588a.png)

**Comment by pbiecek** [comment]
Good idea!

**Comment by pbiecek** [comment]
lack of hands, will not be fixed soon
