### ISSUE TITLE
Optimization: Use QR distribution to calculate LRT statistics for nested models

### ISSUE THREAD

**Issue by durszlaczek** [MI2DataLab/factorMerger#62]
More may be found here: https://arxiv.org/abs/1505.04008

**Comment by pbiecek** [comment]
as in #61 I'm not sure how easy it is to go beyond lm/glm models
it may be a nice feature dedicated to lm models

**Comment by pbiecek** [comment]
that is a very big thing
lack of hands, will not be fixed soon
